# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Shorts
email: shorts@avl.la
description: >- # this means to ignore newlines until "baseurl:"
  Personal URL shortener.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://s.avl.la" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:slug
timezone: America/Sao_Paulo

timeout: 10

twitter_username: aveiiar
github_username:  matheusavellar

# [Ref] stackoverflow.com/a/25597026/4824627
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]


# Long slugs for copying later
# 7brlhkkz2jgxkljem3ic45e7
# mbe4kbrjkhjjmm8amnq7t5um
# vgeoa9xl4vveuripvxzepiqr
# mwrunnsuyvwf79ukfpm476m9
# uzpheufhec5s62qp8gy8uxav